<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-01-07T09:39:10+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.4.3',
    'version_db_installed' => '20180716000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1546600924,
        'do_page_reindex_check' => false,
        'latest_version' => '8.4.3',
    ],
];
