<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-01-04T12:19:53+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'zerobloat',
        ],
    ],
];
